### PR TITLE
Граур А.А., гр. 3530901/10006

### PR DESCRIPTION
**Pull request by argraur**

### CODE REVIEW

**Comment by argraur** [comment]
Oh so it doesn't run `gradle` and wants exactly gradle wrapper (`gradlew`)?

**Comment by Saloed** [comment]
Yes, it requires a gradle wrapper `gradlew` since it's a proper way of gradle build system usage.

**Comment by argraur** [comment]
@Saloed sorry for bothering you again, but I was just looking into others' pull requests and noticed that CI doesn't make `gradlew` executable prior trying to run it, that's quite a problem for those who were doing this task in Windows system, so I think you should add an extra step that makes `gradlew` executable or mention this matter in README that Windows users should change file permissions using `git update-index --chmod=+x gradlew`.

**Comment by Saloed** [comment]
Thx for your message. This is a known issue and I am currently thinking of a gracefull solution. Since it's better to help students who encounter this problem to overcome it, I'll change the readme file according to your suggestion.

**Pull request closed without merging**
